// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3hYotm7rOX1NHPXBxFvNgbiJ5tiaHFYc',
    appId: '1:618104758502:android:932aded1ced73475f2db27',
    messagingSenderId: '618104758502',
    projectId: 'gymphile-83234',
    databaseURL: 'https://gymphile-83234-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gymphile-83234.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYFbL45bf3zXssHRdwJ86KJXSls7F50Mk',
    appId: '1:618104758502:ios:9770c30ee254ac8bf2db27',
    messagingSenderId: '618104758502',
    projectId: 'gymphile-83234',
    databaseURL: 'https://gymphile-83234-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gymphile-83234.appspot.com',
    iosClientId: '618104758502-e2tqji66ifmal5hjcgr2gf9kimst3dt2.apps.googleusercontent.com',
    iosBundleId: 'com.gymphile.gymphile',
  );
}
